spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
  mail:
    host: smtp.qq.com
    username: 928843846@qq.com
    password: ialewffybeyzbdgb
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mail:
  fromMail:
    addr: 928843846@qq.com