spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.188.241/security?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 928843846@qq.com
    password: ialewffybeyzbdgb
    default-encoding: utf-8
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 47.98.188.241:9300
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mail:
  fromMail:
    addr: 928843846@qq.com